version: '3.8'

services:
  api:
    build: .
    container_name: nest_msg_api
    ports:
      - "3333:3333"
    depends_on:
      - rabbitmq
      - postgres    
    volumes:
      - .:/home/node/nest  

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: nest_msg_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - postgres:/var/lib/postgresql/data  

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"